apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.WebApp.Name }}
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.WebApp.Name }}
  endpoints:
    - port: http
      interval: 15s
      path: /prometheus
