name: Deploy Backend Monitoring prod

on:
  workflow_dispatch:

permissions: {}
concurrency: backend-monitoring-prod

jobs:
  deploy-backend-monitoring-prod:
    name: Deploy Backend Monitoring Helm Chart into Cloud Platform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to the cluster
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${{ secrets.KUBE_NAMESPACE }}
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Deploy monitoring Helm chart
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
        run: |
          helm upgrade --install stg-track-my-case-monitoring ./charts/stg-track-my-case-monitoring \
            -f ./charts/stg-track-my-case-monitoring/values-prod.yaml \
            --namespace $KUBE_NAMESPACE \
            --wait
